version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
jobs:
  build_and_deploy_mainnet:
    docker:
      - image: "cimg/node:14.17"
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      - restore_cache:
          key: voltswapinfo-deps-{{ checksum "package.json" }}
      - run:
          name: install yarn dependencies
          command: yarn
      - save_cache:
          key: voltswapinfo-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: production build
          command: REACT_APP_NETWORK=mainnet yarn build
      - run:
          name: s3 sync
          command: aws s3 sync ./build/ s3://charts-base-voltswap-finance/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E33DW1PGWOBZFE --paths "/*"
      - slack/notify:
          event: fail
          mentions: "UE72CTLEB,UB19CQM8W,U01UP0AH5CK"
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_mainnet:
          context:
            - aws-2023
            - slack-secrets
          filters:
            # tags:
            #   only: /^v.*/
            branches:
              only:
                - base
